functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность пользоваться постраничным выводом товаров
  - На странице товара и в каталоге должны выводиться название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге после добавления товара в корзину
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины
  - На странице корзины пользователь должен иметь возможность продолжить выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера
non-functional: 
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Должна быть реализована возможность регистрации и авторизации пользователя 
  - Пользователь должен иметь возможность отследить заказ
  - Пользователь должен быть уведомлен о сборе его персональных данных (куки)
  - Фильтры и поиск должны корректно работать вместе
  - Сайт должен иметь адаптивную версию для планшетов
  - При большом количестве пользователей система оплаты должна оставаться работоспособной
  - При обновлении страницы выбранный язык должен сохраняться

